//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindMyBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_book_detail
    {
        public int book_id { get; set; }
        public string book_name { get; set; }
        public string book_isbn_number { get; set; }
        public double book_price { get; set; }
        public System.DateTime book_published_date { get; set; }
        public string book_language { get; set; }
        public int pages { get; set; }
        public string rating { get; set; }
        public int author_id_FK { get; set; }
        public int publisher_id_FK { get; set; }
        public int book_status_id_FK { get; set; }
    }
}
